name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  SOLUTION_PATH: src/Our.Umbraco.InvisibleNodes.sln

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          6.x
    - name: Restore
      run: dotnet restore ${{ env.SOLUTION_PATH }}
    - name: Build
      run: dotnet build --no-restore ${{ env.SOLUTION_PATH }}
    - name: Test
      run: dotnet test --no-build --verbosity normal ${{ env.SOLUTION_PATH }}
