name: CI

on:
  push:
    branches: ["v15/dev"]
  pull_request:
    branches: ["v15/dev"]

env:
  SOLUTION_PATH: src/Our.Umbraco.InvisibleNodes.sln
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          8.x
    - name: Cache NuGet Packages
      uses: actions/cache@v3
      with:
        path: ${{ github.workspace }}/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
    - name: Restore
      run: dotnet restore --locked-mode ${{ env.SOLUTION_PATH }}
    - name: Build
      run: dotnet build --no-restore ${{ env.SOLUTION_PATH }}
    - name: Test
      run: dotnet test --no-build --verbosity normal ${{ env.SOLUTION_PATH }}
