name: Release

on:
  release:
    types: ["created"]

env:
  SOLUTION_PATH: src/Our.Umbraco.InvisibleNodes.sln
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

jobs:
  build:
    runs-on: windows-latest
    permissions:
      packages: write
      contents: read
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          8.x
          9.x
    - name: Cache NuGet Packages
      uses: actions/cache@v3
      with:
        path: ${{ github.workspace }}/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
    - name: Restore
      run: dotnet restore --locked-mode ${{ env.SOLUTION_PATH }}
    - name: Build
      run: dotnet build --no-restore -c Release ${{ env.SOLUTION_PATH }}
    - name: Pack
      run: dotnet pack --no-build -c Release ${{ env.SOLUTION_PATH }} -o publish/
    - name: Publish
      run: gci -Recurse -Filter *.nupkg ./publish/ | foreach { dotnet nuget push $_.FullName -k ${{ secrets.NUGET_API_KEY }} -s nuget.org --skip-duplicate }
