name: Release

on:
  release:
    types: ["created"]

env:
  SOLUTION_PATH: src/Our.Umbraco.InvisibleNodes.sln

jobs:
  build:
    runs-on: windows-latest
    permissions:
      packages: write
      contents: read
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          6.x
    - name: Restore
      run: dotnet restore ${{ env.SOLUTION_PATH }}
    - name: Build
      run: dotnet build --no-restore -c Release ${{ env.SOLUTION_PATH }}
    - name: Pack
      run: dotnet pack --no-build -c Release ${{ env.SOLUTION_PATH }} -o publish/
    - name: Publish
      run: dotnet nuget push "./publish/*.nupkg" -k ${{ secrets.NUGET_API_KEY }} -s nuget.org --skip-duplicates
